### ISSUE TITLE
lnk2019 error

### ISSUE THREAD

**Issue by xyxyxiaoyan** [desktop-app/lib_ui#29]
mainwindow.cpp.obj:-1: error: LNK2019: unresolved external symbol "class rpl::producer<struct rpl::empty_value,struct rpl::no_error,class rpl::details::type_erased_generator<struct rpl::empty_value,struct rpl::no_error> > __cdecl crl::on_main_update_requests(void)" (?on_main_update_requests@crl@@YA?AV?$producer@Uempty_value@rpl@@Uno_error@2@V?$type_erased_generator@Uempty_value@rpl@@Uno_error@2@@details@2@@rpl@@XZ) referenced in function "public: __thiscall MainWindow::MainWindow(class QWidget *)" (??0MainWindow@@QAE@PAVQWidget@@@Z)

**Comment by john-preston** [comment]
This should be provided by the app.
