### ISSUE TITLE
#7 causes CJK to always use Microsoft YaHei

### ISSUE THREAD

**Issue by Raymonf** [desktop-app/lib_ui#9]
https://github.com/desktop-app/lib_ui/blob/725d768f0ff1c22f6b477c28c324c20cbf2419da/ui/style/style_core_font.cpp#L197

Inserting Microsoft YaHei here first causes Microsoft YaHei to be the default font for CJK.

It doesn't matter if Microsoft JhengHei UI, Yu Gothic UI or whatever that string of escape sequences is are in the list. At least CJK versions of Windows ship with all of those fonts, if not all versions.

Different languages (and even simplified script vs. traditional script in Chinese) use different standards for text. Could that commit be partially reverted for the time being?

**Comment by ilya-fedin** [comment]
That should be fixed by https://github.com/desktop-app/patches/pull/1

**Comment by Raymonf** [comment]
@ilya-fedin Noted, but wouldn't it still fall back to YaHei if the commit from #7 is still merged?

**Comment by ilya-fedin** [comment]
> but wouldn't it still fall back to YaHei if the commit from #7 is still merged?

After desktop-app/patches#1 is merged, these substitutions could be safely removed
