### ISSUE TITLE
Qt6 only functions is used

### ISSUE THREAD

**Issue by vitlav** [desktop-app/lib_ui#91]
Since 

commit 89be8d23fcd032c3410b3e17f294b2c3701c8d00
```
Author: Ilya Fedin <fedin-ilja2010@ya.ru>
Date:   Sun Mar 20 09:03:23 2022 +0400

    Set screen for tooltip
```

commit 39176f619e699103b9ca3941ca6a54aa9b77f829
```
Author: Ilya Fedin <fedin-ilja2010@ya.ru>
Date:   Sun Mar 20 09:03:14 2022 +0400

    Set screen for popup menu
```

I got
```
Telegram/lib_ui/ui/widgets/tooltip.cpp:120:3: error: ‘setScreen’ was not declared in this scope;
Telegram/lib_ui/ui/widgets/popup_menu.cpp:764:3: error: ‘setScreen’ was not declared in this scope;
```

when build with Qt 5 (QtWidget has no setScreen here)

**Comment by vitlav** [comment]
The same with https://github.com/telegramdesktop/tdesktop/pull/24226

**Comment by ilya-fedin** [comment]
Please don't create issues at submodules as no one looks at them.

**Comment by vitlav** [comment]
> Please don't create issues at submodules as no one looks at them.

Ohh, sorry! Will I create that issue in the main repo?

May be you wish disable issue creating for this repo?
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/disabling-issues

**Comment by ilya-fedin** [comment]
> Ohh, sorry! Will I create that issue in the main repo?

Use issue search.

> May be you wish disable issue creating for this repo?

Well, I have no management rights and I proposed this to the person who has, but was ignored.
